<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
		<div class="wrapper">
			<h1>
				Napkyn CE
			</h1>
			<form>
			</form>
		</div>
	</body>
	<footer>
		<div class="wrapper">
			<p>
				2010-2013 Napkyn
			</p>
		</div>
	</footer>
	<style>
		html {
		background-color:#88AA54;
		font-family: Arial, Helvetica, sans-serif;
		}
		body {
		width: 100%;
		}
		body .wrapper {
		width: 15%;
		margin: 0 10% 0 10%;
		}
		h1 { 
		color:#FFFFFF;
		font-size:50px;
		}
	</style>
</html>